export const skills = [
  "React",
  "Node.js",
  "Express",
  "MongoDB",
  "Neo4j",
  "JavaScript",
  "TypeScript",
  "Redux",
  "Tailwind CSS",
  "Material UI",
  "HTML",
  "CSS",
  "Git",
  "Docker",
  "AWS",
  "Redis",
  "GraphQL",
  "REST API",
  "JWT",
  "Python",
  "Java",
  "Spring Boot",
  "Next.js",
  "Vite",
  "CI/CD",
  "Linux",
  "Kubernetes",
  "PostgreSQL",
  "MySQL",
  "Firebase",
];

export const companies = [
  "Northstar Health",
  "Meridian Finance",
  "Atlas Commerce",
  "Cloudline Systems",
  "Bluepeak Labs",
  "Vertex Learning",
  "Ember Mobility",
  "Harbor Data",
  "Luma Retail",
  "Orion Platforms",
];

export const technologies = [
  "React",
  "Node.js",
  "MongoDB",
  "Neo4j",
  "Docker",
  "Redis",
  "AWS",
  "Tailwind CSS",
  "Express",
  "TypeScript",
];

export const certifications = [
  "AWS Developer Associate",
  "Azure Fundamentals",
  "Docker Certified Associate",
  "MongoDB Associate",
  "React Advanced",
  "Oracle Java",
  "Google Cloud Associate",
  "CKAD",
  "GitHub Foundations",
  "Node.js Certified",
];

export const projects = [
  "Care Coordination Platform",
  "Payments Risk Engine",
  "Supply Chain Control Tower",
  "Customer Identity Service",
  "Learning Analytics Suite",
  "Talent Intelligence Platform",
  "Fleet Operations Console",
  "Merchant Insights Platform",
  "Developer Productivity Hub",
  "Cloud Cost Optimizer",
  "Patient Scheduling System",
  "Experimentation Platform",
  "Knowledge Base Assistant",
  "Workforce Planning Portal",
  "Subscription Billing Service",
  "Data Quality Monitor",
  "Incident Response Center",
  "Partner Integration Hub",
  "Forecasting Workbench",
  "Document Lifecycle Service",
];

export const roles = [
  "Senior Frontend Engineer",
  "Backend Engineer",
  "Full Stack Engineer",
  "Platform Engineer",
  "Data Engineer",
  "ML Platform Engineer",
  "Product Frontend Engineer",
  "API Engineer",
  "Frontend Engineer",
];

export const candidates = [
  {
    id: 1,
    name: "Maya Rao",
    role: "Senior Frontend Engineer",
    email: "maya.rao@graphhire.example",
    experience: 6,
    location: "Bengaluru, India",
    availability: "Available in 2 weeks",
    summary: "Designs accessible, high-performance React experiences for B2B products.",
  },
  {
    id: 2,
    name: "Arjun Sethi",
    role: "Backend Engineer",
    email: "arjun.sethi@graphhire.example",
    experience: 5,
    location: "Pune, India",
    availability: "Available now",
    summary: "Builds reliable APIs and data services for regulated product teams.",
  },
  {
    id: 3,
    name: "Elena Park",
    role: "Platform Engineer",
    email: "elena.park@graphhire.example",
    experience: 7,
    location: "Remote, APAC",
    availability: "Available in 4 weeks",
    summary: "Creates secure cloud platforms and developer enablement tooling.",
  },
  {
    id: 4,
    name: "Noah Williams",
    role: "Full Stack Engineer",
    email: "noah.williams@graphhire.example",
    experience: 5,
    location: "Remote, EMEA",
    availability: "Available now",
    summary: "Ships customer-facing products across React, APIs, and cloud infrastructure.",
  },
  {
    id: 5,
    name: "Isha Nair",
    role: "Data Engineer",
    email: "isha.nair@graphhire.example",
    experience: 6,
    location: "Hyderabad, India",
    availability: "Available in 3 weeks",
    summary: "Builds resilient analytics pipelines and data products for operations teams.",
  },
  {
    id: 6,
    name: "Sofia Martinez",
    role: "Product Frontend Engineer",
    email: "sofia.martinez@graphhire.example",
    experience: 4,
    location: "Remote, Americas",
    availability: "Available now",
    summary: "Turns complex operations workflows into intuitive product interfaces.",
  },
  {
    id: 7,
    name: "Daniel Kim",
    role: "API Engineer",
    email: "daniel.kim@graphhire.example",
    experience: 6,
    location: "Seoul, South Korea",
    availability: "Available in 2 weeks",
    summary: "Specializes in integration platforms, graph APIs, and service reliability.",
  },
  {
    id: 8,
    name: "Amina Okafor",
    role: "ML Platform Engineer",
    email: "amina.okafor@graphhire.example",
    experience: 7,
    location: "Lagos, Nigeria",
    availability: "Available in 4 weeks",
    summary: "Operationalizes machine-learning workloads on reliable cloud platforms.",
  },
  {
    id: 9,
    name: "Liam Chen",
    role: "Frontend Engineer",
    email: "liam.chen@graphhire.example",
    experience: 3,
    location: "Singapore",
    availability: "Available now",
    summary: "Builds polished interfaces and design-system foundations for product teams.",
  },
  {
    id: 10,
    name: "Priyanka Shah",
    role: "Full Stack Engineer",
    email: "priyanka.shah@graphhire.example",
    experience: 7,
    location: "Ahmedabad, India",
    availability: "Available in 2 weeks",
    summary: "Leads end-to-end delivery for data-intensive customer platforms.",
  },
];

export const candidateSkills = {
  1: [
    { name: "React", level: "Expert", years: 5 },
    { name: "TypeScript", level: "Advanced", years: 4 },
    { name: "JavaScript", level: "Expert", years: 6 },
    { name: "HTML", level: "Expert", years: 6 },
    { name: "CSS", level: "Expert", years: 6 },
    { name: "Tailwind CSS", level: "Advanced", years: 3 },
  ],
  2: [
    { name: "Node.js", level: "Expert", years: 5 },
    { name: "Express", level: "Advanced", years: 4 },
    { name: "TypeScript", level: "Advanced", years: 3 },
    { name: "PostgreSQL", level: "Advanced", years: 4 },
    { name: "REST API", level: "Expert", years: 5 },
    { name: "JWT", level: "Advanced", years: 3 },
  ],
  3: [
    { name: "AWS", level: "Expert", years: 5 },
    { name: "Docker", level: "Expert", years: 5 },
    { name: "Kubernetes", level: "Advanced", years: 4 },
    { name: "Linux", level: "Advanced", years: 6 },
    { name: "CI/CD", level: "Advanced", years: 4 },
    { name: "Git", level: "Expert", years: 7 },
  ],
  4: [
    { name: "React", level: "Advanced", years: 4 },
    { name: "Node.js", level: "Advanced", years: 4 },
    { name: "TypeScript", level: "Advanced", years: 3 },
    { name: "GraphQL", level: "Advanced", years: 3 },
    { name: "Docker", level: "Intermediate", years: 2 },
    { name: "PostgreSQL", level: "Advanced", years: 3 },
  ],
  5: [
    { name: "Python", level: "Expert", years: 6 },
    { name: "PostgreSQL", level: "Advanced", years: 5 },
    { name: "Docker", level: "Advanced", years: 3 },
    { name: "AWS", level: "Intermediate", years: 3 },
    { name: "Linux", level: "Advanced", years: 5 },
    { name: "Git", level: "Advanced", years: 5 },
  ],
  6: [
    { name: "React", level: "Advanced", years: 4 },
    { name: "JavaScript", level: "Expert", years: 5 },
    { name: "TypeScript", level: "Intermediate", years: 2 },
    { name: "Tailwind CSS", level: "Advanced", years: 3 },
    { name: "Material UI", level: "Advanced", years: 2 },
    { name: "HTML", level: "Expert", years: 5 },
  ],
  7: [
    { name: "Node.js", level: "Expert", years: 6 },
    { name: "Express", level: "Advanced", years: 5 },
    { name: "GraphQL", level: "Advanced", years: 4 },
    { name: "Neo4j", level: "Intermediate", years: 2 },
    { name: "REST API", level: "Advanced", years: 5 },
    { name: "Redis", level: "Intermediate", years: 2 },
  ],
  8: [
    { name: "Python", level: "Expert", years: 7 },
    { name: "AWS", level: "Advanced", years: 4 },
    { name: "Docker", level: "Advanced", years: 4 },
    { name: "Kubernetes", level: "Advanced", years: 3 },
    { name: "Linux", level: "Advanced", years: 5 },
    { name: "CI/CD", level: "Intermediate", years: 2 },
  ],
  9: [
    { name: "React", level: "Intermediate", years: 2 },
    { name: "TypeScript", level: "Intermediate", years: 1 },
    { name: "Redux", level: "Intermediate", years: 1 },
    { name: "HTML", level: "Advanced", years: 3 },
    { name: "CSS", level: "Advanced", years: 3 },
    { name: "Git", level: "Advanced", years: 3 },
  ],
  10: [
    { name: "React", level: "Expert", years: 6 },
    { name: "Node.js", level: "Expert", years: 6 },
    { name: "TypeScript", level: "Advanced", years: 5 },
    { name: "GraphQL", level: "Advanced", years: 4 },
    { name: "AWS", level: "Advanced", years: 4 },
    { name: "Docker", level: "Intermediate", years: 3 },
  ],
};

export const candidateCompany = {
  1: "Northstar Health",
  2: "Meridian Finance",
  3: "Cloudline Systems",
  4: "Atlas Commerce",
  5: "Harbor Data",
  6: "Vertex Learning",
  7: "Orion Platforms",
  8: "Bluepeak Labs",
  9: "Luma Retail",
  10: "Ember Mobility",
};

export const candidateProjects = {
  1: ["Care Coordination Platform", "Merchant Insights Platform"],
  2: ["Payments Risk Engine", "Subscription Billing Service"],
  3: ["Cloud Cost Optimizer", "Incident Response Center"],
  4: ["Learning Analytics Suite", "Experimentation Platform"],
  5: ["Forecasting Workbench", "Data Quality Monitor"],
  6: ["Learning Analytics Suite", "Workforce Planning Portal"],
  7: ["Talent Intelligence Platform", "Partner Integration Hub"],
  8: ["Knowledge Base Assistant", "Forecasting Workbench"],
  9: ["Merchant Insights Platform", "Experimentation Platform"],
  10: ["Experimentation Platform", "Supply Chain Control Tower"],
};

export const candidateCertification = {
  1: "React Advanced",
  2: "Node.js Certified",
  3: "Docker Certified Associate",
  4: "AWS Developer Associate",
  5: "Google Cloud Associate",
  6: "React Advanced",
  7: "MongoDB Associate",
  8: "CKAD",
  9: "GitHub Foundations",
  10: "Azure Fundamentals",
};

export const projectSkills = {
  "Care Coordination Platform": ["React", "TypeScript", "REST API", "AWS"],
  "Payments Risk Engine": ["Node.js", "Express", "PostgreSQL", "JWT"],
  "Supply Chain Control Tower": ["React", "Node.js", "MongoDB", "Docker"],
  "Customer Identity Service": ["Node.js", "Express", "JWT", "Redis"],
  "Learning Analytics Suite": ["React", "TypeScript", "GraphQL", "PostgreSQL"],
  "Talent Intelligence Platform": ["React", "Node.js", "Neo4j", "GraphQL"],
  "Fleet Operations Console": ["React", "Docker", "AWS", "Redis"],
  "Merchant Insights Platform": ["React", "Redux", "TypeScript", "REST API"],
  "Developer Productivity Hub": ["Node.js", "Docker", "CI/CD", "Git"],
  "Cloud Cost Optimizer": ["Python", "AWS", "Docker", "PostgreSQL"],
  "Patient Scheduling System": ["Java", "Spring Boot", "MySQL", "REST API"],
  "Experimentation Platform": ["React", "TypeScript", "GraphQL", "AWS"],
  "Knowledge Base Assistant": ["Python", "AWS", "Docker", "Linux"],
  "Workforce Planning Portal": ["React", "Node.js", "MongoDB", "JWT"],
  "Subscription Billing Service": ["Node.js", "Express", "PostgreSQL", "Redis"],
  "Data Quality Monitor": ["Python", "PostgreSQL", "Docker", "CI/CD"],
  "Incident Response Center": ["Linux", "Docker", "Kubernetes", "AWS"],
  "Partner Integration Hub": ["Node.js", "GraphQL", "REST API", "Neo4j"],
  "Forecasting Workbench": ["Python", "PostgreSQL", "AWS", "Git"],
  "Document Lifecycle Service": ["Node.js", "MongoDB", "AWS", "Docker"],
};

// Curated, directed learning or complementary-technology paths used by the
// Skill Gap Explorer. These are intentionally domain relationships, not list order.
export const skillRelationships = [
  ["HTML", "CSS"],
  ["JavaScript", "TypeScript"],
  ["JavaScript", "React"],
  ["React", "Redux"],
  ["React", "Next.js"],
  ["React", "Tailwind CSS"],
  ["React", "Material UI"],
  ["Node.js", "Express"],
  ["Node.js", "REST API"],
  ["Node.js", "GraphQL"],
  ["Express", "JWT"],
  ["MongoDB", "Redis"],
  ["Docker", "Kubernetes"],
  ["Linux", "Docker"],
  ["AWS", "CI/CD"],
  ["Git", "CI/CD"],
  ["Python", "PostgreSQL"],
  ["Java", "Spring Boot"],
  ["Java", "MySQL"],
  ["Neo4j", "GraphQL"],
];
