export const skills = [
  "React",
  "Node.js",
  "Express",
  "MongoDB",
  "Neo4j",
  "JavaScript",
  "TypeScript",
  "Redux",
  "Tailwind CSS",
  "Material UI",
  "HTML",
  "CSS",
  "Git",
  "Docker",
  "AWS",
  "Redis",
  "GraphQL",
  "REST API",
  "JWT",
  "Python",
  "Java",
  "Spring Boot",
  "Next.js",
  "Vite",
  "CI/CD",
  "Linux",
  "Kubernetes",
  "PostgreSQL",
  "MySQL",
  "Firebase",
];

export const companies = [
  "Google",
  "Microsoft",
  "Amazon",
  "Netflix",
  "Adobe",
  "Atlassian",
  "Uber",
  "Flipkart",
  "Swiggy",
  "Zomato",
];

export const technologies = [
  "React",
  "Node.js",
  "MongoDB",
  "Neo4j",
  "Docker",
  "Redis",
  "AWS",
  "Tailwind CSS",
  "Express",
  "TypeScript",
];

export const certifications = [
  "AWS Developer Associate",
  "Azure Fundamentals",
  "Docker Certified Associate",
  "MongoDB Associate",
  "React Advanced",
  "Oracle Java",
  "Google Cloud Associate",
  "CKAD",
  "GitHub Foundations",
  "Node.js Certified",
];

export const projects = [
  "CRM Platform",
  "Inventory Management",
  "Learning Management System",
  "Hospital ERP",
  "Chat Application",
  "Payment Gateway",
  "Analytics Dashboard",
  "Recruitment Portal",
  "Hotel Booking",
  "Food Delivery Platform",
  "E-Commerce Platform",
  "AI Chatbot",
  "Task Manager",
  "Expense Tracker",
  "School ERP",
  "Vehicle Tracking",
  "HRMS",
  "Attendance System",
  "Online IDE",
  "Document Management",
];

export const roles = [
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Engineer",
  "DevOps Engineer",
  "Data Engineer",
  "AI/ML Engineer",
];

export const candidates = [
  {
    id: 1,
    name: "Aarav Sharma",
    role: "Frontend Engineer",
    email: "aarav@gmail.com",
    experience: 5,
    location: "Bangalore",
  },
  {
    id: 2,
    name: "Priya Singh",
    role: "Backend Engineer",
    email: "priya@gmail.com",
    experience: 4,
    location: "Pune",
  },
  {
    id: 3,
    name: "Rohan Mehta",
    role: "DevOps Engineer",
    email: "rohan@gmail.com",
    experience: 6,
    location: "Delhi",
  },
  {
    id: 4,
    name: "Neha Kapoor",
    role: "Full Stack Engineer",
    email: "neha@gmail.com",
    experience: 3,
    location: "Mumbai",
  },
  {
    id: 5,
    name: "Karan Verma",
    role: "Data Engineer",
    email: "karan@gmail.com",
    experience: 7,
    location: "Hyderabad",
  },
  {
    id: 6,
    name: "Ananya Das",
    role: "Frontend Engineer",
    email: "ananya@gmail.com",
    experience: 5,
    location: "Chandigarh",
  },
  {
    id: 7,
    name: "Rahul Gupta",
    role: "Backend Engineer",
    email: "rahul@gmail.com",
    experience: 4,
    location: "Noida",
  },
  {
    id: 8,
    name: "Sneha Jain",
    role: "AI/ML Engineer",
    email: "sneha@gmail.com",
    experience: 8,
    location: "Jaipur",
  },
  {
    id: 9,
    name: "Vikas Kumar",
    role: "Frontend Engineer",
    email: "vikas@gmail.com",
    experience: 2,
    location: "Indore",
  },
  {
    id: 10,
    name: "Aditya Rao",
    role: "Full Stack Engineer",
    email: "aditya@gmail.com",
    experience: 6,
    location: "Ahmedabad",
  },
];

export const candidateSkills = {
  1: ["React", "JavaScript", "HTML", "CSS", "Tailwind CSS", "Redux"],
  2: ["Node.js", "Express", "MongoDB", "REST API", "JWT", "Redis"],
  3: ["Docker", "AWS", "Linux", "CI/CD", "Kubernetes", "Git"],
  4: ["React", "Node.js", "MongoDB", "Express", "TypeScript", "Docker"],
  5: ["Python", "PostgreSQL", "Docker", "AWS", "Git", "Redis"],
  6: ["React", "Vite", "Tailwind CSS", "Material UI", "JavaScript", "HTML"],
  7: ["Node.js", "Express", "MongoDB", "Neo4j", "GraphQL", "Redis"],
  8: ["Python", "Java", "AWS", "Docker", "Linux", "CI/CD"],
  9: ["React", "Redux", "TypeScript", "HTML", "CSS", "Git"],
  10: ["React", "Node.js", "MongoDB", "Docker", "AWS", "GraphQL"],
};

export const candidateCompany = {
  1: "Google",
  2: "Microsoft",
  3: "Amazon",
  4: "Netflix",
  5: "Adobe",
  6: "Atlassian",
  7: "Uber",
  8: "Flipkart",
  9: "Swiggy",
  10: "Zomato",
};

export const candidateProjects = {
  1: ["CRM Platform", "Analytics Dashboard"],
  2: ["Recruitment Portal", "HRMS"],
  3: ["Vehicle Tracking", "Hospital ERP"],
  4: ["Chat Application", "Payment Gateway"],
  5: ["AI Chatbot", "Document Management"],
  6: ["Expense Tracker", "Task Manager"],
  7: ["Recruitment Portal", "Online IDE"],
  8: ["Learning Management System", "School ERP"],
  9: ["Food Delivery Platform", "Hotel Booking"],
  10: ["E-Commerce Platform", "Inventory Management"],
};

export const candidateCertification = {
  1: "React Advanced",
  2: "Node.js Certified",
  3: "Docker Certified Associate",
  4: "AWS Developer Associate",
  5: "Google Cloud Associate",
  6: "React Advanced",
  7: "MongoDB Associate",
  8: "CKAD",
  9: "GitHub Foundations",
  10: "Azure Fundamentals",
};

export const projectSkills = {
  "CRM Platform": ["React", "Node.js", "MongoDB", "JWT"],
  "Inventory Management": ["React", "Express", "MongoDB"],
  "Learning Management System": ["React", "Node.js", "Redis"],
  "Hospital ERP": ["Java", "Spring Boot", "MySQL"],
  "Chat Application": ["React", "Node.js", "REST API"],
  "Payment Gateway": ["Node.js", "REST API", "JWT"],
  "Analytics Dashboard": ["React", "GraphQL", "TypeScript"],
  "Recruitment Portal": ["React", "Node.js", "Neo4j"],
  "Hotel Booking": ["React", "Express", "MongoDB"],
  "Food Delivery Platform": ["React", "Node.js", "Redis"],
  "E-Commerce Platform": ["React", "Node.js", "MongoDB"],
  "AI Chatbot": ["Python", "Docker", "AWS"],
  "Task Manager": ["React", "Express", "MongoDB"],
  "Expense Tracker": ["React", "Redux", "Firebase"],
  "School ERP": ["Java", "Spring Boot", "MySQL"],
  "Vehicle Tracking": ["Docker", "AWS", "Redis"],
  HRMS: ["React", "Node.js", "MongoDB"],
  "Attendance System": ["React", "Firebase", "REST API"],
  "Online IDE": ["React", "Node.js", "Docker"],
  "Document Management": ["MongoDB", "Node.js", "AWS"],
};

export const skillMetadata = {
  React: { level: "Expert", years: 5 },
  "Node.js": { level: "Advanced", years: 4 },
  Express: { level: "Advanced", years: 4 },
  MongoDB: { level: "Advanced", years: 4 },
  Neo4j: { level: "Intermediate", years: 2 },
  JavaScript: { level: "Expert", years: 6 },
  TypeScript: { level: "Advanced", years: 3 },
  Redux: { level: "Advanced", years: 3 },
  "Tailwind CSS": { level: "Advanced", years: 3 },
  "Material UI": { level: "Advanced", years: 3 },
  HTML: { level: "Expert", years: 6 },
  CSS: { level: "Expert", years: 6 },
  Git: { level: "Expert", years: 6 },
  Docker: { level: "Advanced", years: 4 },
  AWS: { level: "Intermediate", years: 2 },
  Redis: { level: "Intermediate", years: 2 },
  GraphQL: { level: "Intermediate", years: 2 },
  "REST API": { level: "Expert", years: 5 },
  JWT: { level: "Advanced", years: 4 },
  Python: { level: "Advanced", years: 4 },
  Java: { level: "Intermediate", years: 3 },
  "Spring Boot": { level: "Intermediate", years: 2 },
  "Next.js": { level: "Intermediate", years: 2 },
  Vite: { level: "Advanced", years: 2 },
  "CI/CD": { level: "Intermediate", years: 2 },
  Linux: { level: "Advanced", years: 4 },
  Kubernetes: { level: "Intermediate", years: 2 },
  PostgreSQL: { level: "Intermediate", years: 3 },
  MySQL: { level: "Advanced", years: 4 },
  Firebase: { level: "Intermediate", years: 2 },
};
